// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf8q-Jke84tdNXfW8BlMjMXyGcqqSjvc0',
    appId: '1:582303986068:web:5fe2bec070b4aa13449f81',
    messagingSenderId: '582303986068',
    projectId: 'instagram-sample-4b16e',
    authDomain: 'instagram-sample-4b16e.firebaseapp.com',
    storageBucket: 'instagram-sample-4b16e.firebasestorage.app',
    measurementId: 'G-K5L4ZZYV5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRNJnSaBU9ZRZgA1Sj-fTb7dTbKeXalqQ',
    appId: '1:582303986068:android:2c94bc1d9293d83c449f81',
    messagingSenderId: '582303986068',
    projectId: 'instagram-sample-4b16e',
    storageBucket: 'instagram-sample-4b16e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGlczUUGrdbt0vhIpbD621seYsKpDKai8',
    appId: '1:582303986068:ios:6fb51b1307bf91e5449f81',
    messagingSenderId: '582303986068',
    projectId: 'instagram-sample-4b16e',
    storageBucket: 'instagram-sample-4b16e.firebasestorage.app',
    iosBundleId: 'com.example.instagramPosts',
  );
}
